/*
 * generated by Xtext
 */
package at.bestsolution.dart.service.spec.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DartServiceSpecUiModule extends at.bestsolution.dart.service.spec.ui.AbstractDartServiceSpecUiModule {
	public DartServiceSpecUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
