/*
 * generated by Xtext
 */
package at.bestsolution.dart.service.spec.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDartServiceSpecValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(at.bestsolution.dart.service.spec.dartServiceSpec.DartServiceSpecPackage.eINSTANCE);
		return result;
	}
}
