/*
 * generated by Xtext
 */
package at.bestsolution.dart.service.spec;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DartServiceSpecRuntimeModule extends at.bestsolution.dart.service.spec.AbstractDartServiceSpecRuntimeModule {

}
