/*
 * generated by Xtext
 */
package at.bestsolution.dart.service.spec;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DartServiceSpecStandaloneSetup extends DartServiceSpecStandaloneSetupGenerated{

	public static void doSetup() {
		new DartServiceSpecStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

