/*
 * generated by Xtext
 */
package at.bestsolution.dart.service.spec.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.bestsolution.dart.service.spec.ui.internal.DartServiceSpecActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DartServiceSpecExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DartServiceSpecActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DartServiceSpecActivator.getInstance().getInjector(DartServiceSpecActivator.AT_BESTSOLUTION_DART_SERVICE_SPEC_DARTSERVICESPEC);
	}
	
}
