/*
 * generated by Xtext
 */
package at.bestsolution.dart.service.spec.ui.contentassist

import at.bestsolution.dart.service.spec.ui.contentassist.AbstractDartServiceSpecProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class DartServiceSpecProposalProvider extends AbstractDartServiceSpecProposalProvider {
}
